systemGroupAndUsers:
  groups:
  - name: staff
  - name: website1
  - name: website2
  users:
  - name: userwithsudo
    password: saHW9GdxihkGQ
    groupMember: 
    homeDirectory: 
    defaultShell: /bin/bash
    superUser: true
  - name: userWebsite1
    password: saHW9GdxihkGQ
    groupMember: 
    homeDirectory: 
    defaultShell: /bin/bash
    superUser: false
  - name: userWebsite2
    password: saHW9GdxihkGQ
    groupMember:
    - name: website2
    homeDirectory: 
    defaultShell: /bin/bash
    superUser: false

